extends: airbnb
env:
  browser: true
  es6: true
  mocha: true
plugins:
  - chai-friendly
rules:
  import/prefer-default-export: 0
  no-unused-expressions: 0
  chai-friendly/no-unused-expressions: 2
  indent: [2, 2]
  import/no-extraneous-dependencies: 0
globals:
  chai: true
  expect: true
  should: true
  assert: true
  sinon: true

